### ISSUE TITLE
fastsafetensors.patch can't be applied any more

### ISSUE THREAD

**Issue by oparoz** [eugr/spark-vllm-docker#33]
Just tried various builds using: `./build-and-copy.sh` and they all fail with:

```
=> ERROR [stage-0  8/13] RUN patch -p1 -d /usr/local/lib/python3.12/dist-packages < /workspace/vllm/fastsafetensors.patch      0.2s
------
 > [stage-0  8/13] RUN patch -p1 -d /usr/local/lib/python3.12/dist-packages < /workspace/vllm/fastsafetensors.patch:
0.194 patching file vllm/model_executor/model_loader/weight_utils.py
0.194 Hunk #1 succeeded at 30 (offset 2 lines).
0.194 Hunk #2 FAILED at 771.
0.194 1 out of 2 hunks FAILED -- saving rejects to file vllm/model_executor/model_loader/weight_utils.py.rej
------
ERROR: failed to build: failed to solve: process "/bin/sh -c patch -p1 -d /usr/local/lib/python3.12/dist-packages < ${VLLM_BASE_DIR}/fastsafetensors.patch" did not complete successfully: exit code: 1
```

**Comment by heldernoid** [comment]
I commented out `# RUN patch -p1 < fastsafetensors.patch` in `Dockerfile` then ran `./build-and-copy.sh ` again.

**Comment by stavinsky** [comment]
https://github.com/vllm-project/vllm/commit/d9bede0314ba19a3f8336dcaeeeaf9e2c5487053
according to commit message they "fixed" fastsafetensors
hmm also torch 2.10.0 bumped.

**Comment by Balaxxe** [comment]
Can confirm, same failure on a fresh clone today. All three Dockerfile.wheels variants fail (standard, --pre-tf, --pre-flashinfer). The --exp-mxfp4 build completes fine since Dockerfile.mxfp4 doesn't use the patch.

As a temporary workaround you can comment out the patch step in Dockerfile.wheels before building:

bashsed -i 's|^RUN patch -p1|# RUN patch -p1|' Dockerfile.wheels

This obviously means no fastsafetensors support in the resulting image, but it unblocks the build.

**Comment by stavinsky** [comment]
you still can build with previous vllm version like v0.15.0 (I don't remember correctly which one)

There is another potential problem btw 
```
root@0f392a6060e0:/workspace/vllm# vllm
ERROR 02-09 17:10:09 [gpt_oss_triton_kernels_moe.py:46] Failed to import Triton kernels. Please make sure your triton version is compatible. Error: cannot import name 'SparseMatrix' from 'triton_kernels.tensor' (/usr/local/lib/python3.12/dist-packages/triton_kernels/tensor.py)
```

looks like 3.5.1 version of triton is not suitable anymore. I've tried to bump to 3.6.0. Let's have a look what will change

**Comment by eugr** [comment]
Thanks, was just going to create a PSA ticket.

This [PR](https://github.com/vllm-project/vllm/pull/34070) broke the patch, but it's probably not needed anymore. Currently running the build to see if it works in the cluster without the patch. If not, I'll have to adapt the patch to new codebase.

I'm also going to merge my pytorch-base branch that has Triton 3.6.0 by default. Will do shortly if everything succeeds.

**Comment by eugr** [comment]
It's working, will merge in a few minutes!

**Comment by eugr** [comment]
Pushed, should be fixed now - please reopen if you experience any issues.

**Comment by oparoz** [comment]
Tested three builds, all of which completed successfully: `--exp-mxfp4`, `--use-wheels --pre-tf`, and `--use-wheels`.
